version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
    target-branch: "master"
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: "chore(deps)"
  - package-ecosystem: pip
    directory: /src
    schedule:
      interval: weekly
    target-branch: "master"
    ignore:
      - dependency-name: "ultralytics"
    commit-message:
      prefix: "chore(deps)"
