# See help here: https://github.com/marketplace/actions/labeler

python:
  - changed-files:
      - any-glob-to-any-file:
          - model_api/src/**
          - model_converter/src/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - model_api/tests/**
          - model_converter/tests/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - model_api/docs/**
          - model_converter/docs/**
          - "**/*.md"
          - "LICENSE"

build:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - ".pre-commit-config.yaml"
          - "model_api/pyproject.toml"
          - "model_api/uv.lock"
          - "model_converter/pyproject.toml"
          - "model_converter/uv.lock"
          - "**/CMakeLists.txt"

samples:
  - changed-files:
      - any-glob-to-any-file:
          - model_api/examples/**
          - model_converter/examples/**
