default_language_version:
  node: 22.10.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  # Ruff version.
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.6.2"
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
      # Run the formatter
      - id: ruff-format

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-setuptools]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint

  # zizmor detects security issues in GitHub Actions workflows.
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.9.0
    hooks:
      - id: zizmor
        args: ["--min-severity", "medium", "--min-confidence", "high"]

  # add bandit for security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args:
          [
            "-c",
            "pyproject.toml",
            "--severity-level",
            "all",
            "--confidence-level",
            "all",
          ]
        additional_dependencies: ["bandit[toml]"]
